import { readFile, writeFile } from "node:fs/promises";
import openapiTS, { astToString } from "openapi-typescript";

const schemaUrl = new URL("../openapi.json", import.meta.url);
const outputUrl = new URL("../../web/src/lib/api/generated.ts", import.meta.url);
const header = `/*
 * Generated from protocol/openapi.json.
 * Do not edit this file directly; run npm run generate:protocol from web/.
 */
`;

const schema = JSON.parse(await readFile(schemaUrl, "utf8"));
const apiErrorCodes = schema.components?.schemas?.ApiErrorCode?.enum;
if (!Array.isArray(apiErrorCodes) || !apiErrorCodes.every((code) => typeof code === "string")) {
  throw new Error("protocol/openapi.json does not define a string ApiErrorCode enum");
}

const ast = await openapiTS(schemaUrl, { alphabetize: true });
const runtimeValues = `
export const apiErrorCodes = ${JSON.stringify(apiErrorCodes, null, 2)} as const satisfies readonly components["schemas"]["ApiErrorCode"][];
`;
const generated = `${header}${astToString(ast)}${runtimeValues}`;

if (process.argv.includes("--write")) {
  await writeFile(outputUrl, generated);
} else {
  const current = await readFile(outputUrl, "utf8").catch(() => "");
  if (current !== generated) {
    throw new Error(
      "Generated API types are stale; run npm run generate:protocol and commit the result."
    );
  }
}
