-- Initial NV-TOSS schema baseline.
--
-- The service had not been released when its development migrations were
-- consolidated. Databases created from the earlier migration history must be
-- rebuilt before running this baseline. Future schema changes belong in new,
-- incremental migration files; do not edit this file after release.

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;

CREATE TABLE public.anonymous_share_sessions (
    id uuid NOT NULL,
    project_id uuid NOT NULL,
    share_link_id uuid NOT NULL,
    session_token_fingerprint bytea NOT NULL,
    display_name text NOT NULL,
    permission text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone,
    last_used_at timestamp with time zone,
    CONSTRAINT anonymous_share_sessions_fingerprint_length CHECK ((octet_length(session_token_fingerprint) = 32)),
    CONSTRAINT anonymous_share_sessions_permission_check CHECK ((permission = ANY (ARRAY['read'::text, 'write'::text])))
);

CREATE TABLE public.audit_events (
    id uuid NOT NULL,
    actor_user_id uuid,
    event_type text NOT NULL,
    payload jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE public.auth_sessions (
    user_id uuid NOT NULL,
    issued_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    user_agent text,
    ip_address text,
    session_token_fingerprint bytea NOT NULL,
    CONSTRAINT auth_sessions_token_fingerprint_length CHECK ((octet_length(session_token_fingerprint) = 32))
);

CREATE TABLE public.auth_settings (
    id integer NOT NULL,
    allow_local_login boolean DEFAULT true NOT NULL,
    allow_local_registration boolean DEFAULT true NOT NULL,
    allow_oidc boolean DEFAULT true NOT NULL,
    oidc_issuer text,
    oidc_client_id text,
    oidc_client_secret text,
    oidc_redirect_uri text,
    oidc_groups_claim text DEFAULT 'groups'::text NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    site_name text DEFAULT 'Typst Collaboration'::text NOT NULL,
    anonymous_mode text DEFAULT 'off'::text NOT NULL,
    announcement text DEFAULT ''::text NOT NULL,
    CONSTRAINT auth_settings_anonymous_mode_check CHECK ((anonymous_mode = ANY (ARRAY['off'::text, 'read_only'::text, 'read_write_named'::text]))),
    CONSTRAINT auth_settings_id_check CHECK ((id = 1))
);

CREATE TABLE public.collab_doc_latest_snapshots (
    project_id uuid NOT NULL,
    upto_update_id bigint NOT NULL,
    state_update bytea NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    content_epoch bigint DEFAULT 0 NOT NULL,
    document_id uuid NOT NULL,
    collaboration_revision bigint NOT NULL,
    CONSTRAINT collab_doc_snapshots_collaboration_revision_nonnegative CHECK ((collaboration_revision >= 0))
);

CREATE TABLE public.collab_doc_updates (
    id bigint NOT NULL,
    project_id uuid NOT NULL,
    user_id uuid,
    kind text NOT NULL,
    payload bytea NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    content_epoch bigint DEFAULT 0 NOT NULL,
    document_id uuid NOT NULL,
    collaboration_revision bigint NOT NULL,
    guest_display_name text,
    CONSTRAINT collab_doc_updates_actor_check CHECK (((user_id IS NULL) OR (guest_display_name IS NULL))),
    CONSTRAINT collab_doc_updates_collaboration_revision_nonnegative CHECK ((collaboration_revision >= 0)),
    CONSTRAINT collab_doc_updates_kind_check CHECK ((kind = ANY (ARRAY['yjs.update'::text, 'yjs.sync'::text])))
);

ALTER TABLE public.collab_doc_updates ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.collab_doc_updates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.comments (
    id uuid NOT NULL,
    project_id uuid NOT NULL,
    actor_user_id uuid,
    body text NOT NULL,
    anchor text,
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE public.documents (
    id uuid NOT NULL,
    project_id uuid NOT NULL,
    path text NOT NULL,
    content text NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    path_revision bigint DEFAULT 0 NOT NULL,
    collaboration_revision bigint DEFAULT 0 NOT NULL,
    change_sequence bigint NOT NULL
);

CREATE SEQUENCE public.documents_change_sequence_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.documents_change_sequence_seq OWNED BY public.documents.change_sequence;

CREATE TABLE public.external_git_checkpoint_queue (
    project_id uuid NOT NULL,
    target_workspace_version bigint NOT NULL,
    captured_workspace_version bigint,
    checkpoint_sha text,
    captured_at timestamp with time zone,
    next_attempt_at timestamp with time zone NOT NULL,
    state text DEFAULT 'pending'::text NOT NULL,
    phase text DEFAULT 'queued'::text NOT NULL,
    attempt_count integer DEFAULT 0 NOT NULL,
    last_attempt_at timestamp with time zone,
    locked_at timestamp with time zone,
    last_error text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT external_git_checkpoint_queue_phase_check CHECK ((phase = ANY (ARRAY['queued'::text, 'snapshot'::text, 'commit_local'::text, 'push_git'::text]))),
    CONSTRAINT external_git_checkpoint_queue_state_check CHECK ((state = ANY (ARRAY['pending'::text, 'processing'::text, 'retry_wait'::text, 'paused'::text])))
);

CREATE TABLE public.external_git_inbound_jobs (
    id uuid NOT NULL,
    project_id uuid NOT NULL,
    provider_instance_id text NOT NULL,
    operation text NOT NULL,
    source_branch text NOT NULL,
    requested_by_user_id uuid NOT NULL,
    state text DEFAULT 'pending'::text NOT NULL,
    phase text DEFAULT 'queued'::text NOT NULL,
    attempt_count integer DEFAULT 0 NOT NULL,
    next_attempt_at timestamp with time zone NOT NULL,
    last_attempt_at timestamp with time zone,
    locked_at timestamp with time zone,
    remote_sha text,
    last_error text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone,
    applied_workspace_version bigint,
    CONSTRAINT external_git_inbound_jobs_operation_check CHECK ((operation = ANY (ARRAY['import'::text, 'sync'::text]))),
    CONSTRAINT external_git_inbound_jobs_phase_check CHECK ((phase = ANY (ARRAY['queued'::text, 'fetch'::text, 'lfs'::text, 'validate'::text, 'assets'::text, 'apply'::text, 'revision'::text, 'complete'::text]))),
    CONSTRAINT external_git_inbound_jobs_provider_instance_id_check CHECK ((provider_instance_id ~ '^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$'::text)),
    CONSTRAINT external_git_inbound_jobs_revision_recovery_check CHECK (((phase <> 'revision'::text) OR ((remote_sha IS NOT NULL) AND (applied_workspace_version IS NOT NULL)))),
    CONSTRAINT external_git_inbound_jobs_state_check CHECK ((state = ANY (ARRAY['pending'::text, 'processing'::text, 'retry_wait'::text, 'paused'::text, 'failed'::text, 'succeeded'::text])))
);

CREATE TABLE public.external_git_oauth_grants (
    user_id uuid NOT NULL,
    provider_account_id text NOT NULL,
    encrypted_access_token bytea NOT NULL,
    encrypted_refresh_token bytea,
    refresh_redirect_uri text NOT NULL,
    scopes text[] DEFAULT '{}'::text[] NOT NULL,
    expires_at timestamp with time zone,
    status text DEFAULT 'active'::text NOT NULL,
    last_error text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    provider_instance_id text NOT NULL,
    provider_username text NOT NULL,
    CONSTRAINT external_git_oauth_grants_refresh_redirect_uri_check CHECK ((length(refresh_redirect_uri) > 0)),
    CONSTRAINT external_git_oauth_grants_provider_instance_id_check CHECK ((provider_instance_id ~ '^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$'::text)),
    CONSTRAINT external_git_oauth_grants_status_check CHECK ((status = ANY (ARRAY['active'::text, 'reauth_required'::text, 'revoked'::text])))
);

CREATE TABLE public.external_git_oauth_attempts (
    state text NOT NULL,
    provider_instance_id text NOT NULL,
    purpose text NOT NULL,
    user_id uuid,
    return_to text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT external_git_oauth_attempts_provider_instance_id_check CHECK ((provider_instance_id ~ '^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$'::text)),
    CONSTRAINT external_git_oauth_attempts_purpose_check CHECK ((purpose = ANY (ARRAY['sign_in'::text, 'connect'::text]))),
    CONSTRAINT external_git_oauth_attempts_user_check CHECK ((((purpose = 'sign_in'::text) AND (user_id IS NULL)) OR ((purpose = 'connect'::text) AND (user_id IS NOT NULL))))
);

CREATE TABLE public.external_git_pending_authors (
    project_id uuid NOT NULL,
    user_id uuid NOT NULL,
    touched_at timestamp with time zone NOT NULL
);

CREATE TABLE public.external_git_pending_guest_authors (
    project_id uuid NOT NULL,
    display_name text NOT NULL,
    touched_at timestamp with time zone NOT NULL
);

CREATE TABLE public.external_git_project_links (
    project_id uuid NOT NULL,
    provider_repository_id text NOT NULL,
    full_path text NOT NULL,
    web_url text NOT NULL,
    clone_url text NOT NULL,
    default_branch text NOT NULL,
    checkpoint_branch text NOT NULL,
    status text DEFAULT 'linking'::text NOT NULL,
    synced_workspace_version bigint DEFAULT 0 NOT NULL,
    last_remote_sha text,
    last_error text,
    linked_by_user_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    provider_instance_id text NOT NULL,
    last_import_branch text,
    last_import_sha text,
    last_import_at timestamp with time zone,
    last_import_error text,
    CONSTRAINT external_git_project_links_provider_instance_id_check CHECK ((provider_instance_id ~ '^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$'::text)),
    CONSTRAINT external_git_project_links_status_check CHECK ((status = ANY (ARRAY['linking'::text, 'active'::text, 'reauth_required'::text, 'conflict'::text, 'error'::text])))
);

CREATE TABLE public.git_bundle_artifacts (
    id uuid NOT NULL,
    project_id uuid NOT NULL,
    event_type text NOT NULL,
    object_key text NOT NULL,
    size_bytes bigint NOT NULL,
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE public.git_pending_authors (
    project_id uuid NOT NULL,
    user_id uuid NOT NULL,
    touched_at timestamp with time zone NOT NULL
);

CREATE TABLE public.git_pending_guest_authors (
    project_id uuid NOT NULL,
    display_name text NOT NULL,
    touched_at timestamp with time zone NOT NULL
);

CREATE TABLE public.git_repositories (
    project_id uuid NOT NULL,
    remote_url text,
    local_path text NOT NULL,
    default_branch text DEFAULT 'main'::text NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    pending_sync boolean DEFAULT false NOT NULL,
    last_server_sync_at timestamp with time zone
);

CREATE TABLE public.git_sync_states (
    project_id uuid NOT NULL,
    branch text DEFAULT 'main'::text NOT NULL,
    last_pull_at timestamp with time zone,
    last_push_at timestamp with time zone,
    has_conflicts boolean DEFAULT false NOT NULL,
    status text DEFAULT 'clean'::text NOT NULL,
    CONSTRAINT git_sync_states_status_check CHECK ((status = ANY (ARRAY['clean'::text, 'receive_pack_import_failed'::text])))
);

CREATE TABLE public.local_accounts (
    user_id uuid NOT NULL,
    password_hash text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE public.object_deletion_queue (
    object_key text NOT NULL,
    next_attempt_at timestamp with time zone NOT NULL,
    attempt_count integer DEFAULT 0 NOT NULL,
    locked_at timestamp with time zone,
    last_error text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT object_deletion_queue_attempt_count_check CHECK ((attempt_count >= 0)),
    CONSTRAINT object_deletion_queue_object_key_check CHECK ((length(btrim(object_key)) > 0))
);

CREATE TABLE public.oidc_states (
    state text NOT NULL,
    nonce text NOT NULL,
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE public.org_oidc_group_role_mappings (
    organization_id uuid NOT NULL,
    group_name text NOT NULL,
    role text NOT NULL,
    granted_at timestamp with time zone NOT NULL,
    CONSTRAINT org_oidc_group_role_mappings_role_check CHECK ((role = ANY (ARRAY['member'::text, 'owner'::text])))
);

CREATE TABLE public.organization_memberships (
    organization_id uuid NOT NULL,
    user_id uuid NOT NULL,
    joined_at timestamp with time zone NOT NULL,
    role text DEFAULT 'member'::text NOT NULL,
    CONSTRAINT organization_memberships_role_check CHECK ((role = ANY (ARRAY['member'::text, 'owner'::text])))
);

CREATE TABLE public.organizations (
    id uuid NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE public.personal_access_tokens (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    label text NOT NULL,
    token_prefix text NOT NULL,
    token_fingerprint bytea NOT NULL,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone,
    last_used_at timestamp with time zone,
    revoked_at timestamp with time zone,
    CONSTRAINT personal_access_tokens_fingerprint_length CHECK ((octet_length(token_fingerprint) = 32))
);

CREATE TABLE public.project_assets (
    id uuid NOT NULL,
    project_id uuid NOT NULL,
    path text NOT NULL,
    object_key text NOT NULL,
    content_type text NOT NULL,
    size_bytes bigint NOT NULL,
    uploaded_by uuid,
    created_at timestamp with time zone NOT NULL,
    inline_data bytea,
    content_revision uuid NOT NULL
);

CREATE TABLE public.project_directories (
    project_id uuid NOT NULL,
    path text NOT NULL,
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE public.project_group_roles (
    project_id uuid NOT NULL,
    group_name text NOT NULL,
    role text NOT NULL,
    granted_at timestamp with time zone NOT NULL,
    CONSTRAINT project_group_roles_role_check CHECK ((role = ANY (ARRAY['Owner'::text, 'ReadWrite'::text, 'ReadOnly'::text])))
);

CREATE TABLE public.project_organization_access (
    project_id uuid NOT NULL,
    organization_id uuid NOT NULL,
    permission text NOT NULL,
    granted_by uuid,
    granted_at timestamp with time zone NOT NULL,
    CONSTRAINT project_organization_access_permission_check CHECK ((permission = ANY (ARRAY['read'::text, 'write'::text])))
);

CREATE TABLE public.project_pdf_artifacts (
    id uuid NOT NULL,
    project_id uuid NOT NULL,
    entry_file_path text NOT NULL,
    content_type text NOT NULL,
    pdf_bytes bytea NOT NULL,
    size_bytes bigint NOT NULL,
    created_by uuid,
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE public.project_roles (
    project_id uuid NOT NULL,
    user_id uuid NOT NULL,
    role text NOT NULL,
    granted_at timestamp with time zone NOT NULL,
    source text DEFAULT 'direct_role'::text NOT NULL,
    CONSTRAINT project_roles_role_check CHECK ((role = ANY (ARRAY['Owner'::text, 'ReadWrite'::text, 'ReadOnly'::text]))),
    CONSTRAINT project_roles_source_check CHECK ((source = ANY (ARRAY['direct_role'::text, 'share_link_invite'::text])))
);

CREATE TABLE public.project_settings (
    project_id uuid NOT NULL,
    entry_file_path text DEFAULT 'main.typ'::text NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    latex_engine text,
    settings_revision bigint DEFAULT 0 NOT NULL,
    CONSTRAINT project_settings_latex_engine_check CHECK (((latex_engine IS NULL) OR (latex_engine = ANY (ARRAY['pdftex'::text, 'xetex'::text]))))
);

CREATE TABLE public.project_share_links (
    id uuid NOT NULL,
    project_id uuid NOT NULL,
    token_prefix text NOT NULL,
    permission text NOT NULL,
    created_by uuid,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone,
    revoked_at timestamp with time zone,
    token_value text NOT NULL,
    CONSTRAINT project_share_links_permission_check CHECK ((permission = ANY (ARRAY['read'::text, 'write'::text])))
);

CREATE TABLE public.project_snapshots (
    id uuid NOT NULL,
    project_id uuid NOT NULL,
    object_key text NOT NULL,
    created_by uuid,
    created_at timestamp with time zone NOT NULL,
    document_count integer NOT NULL,
    byte_size bigint NOT NULL
);

CREATE TABLE public.project_sync_queue (
    project_id uuid NOT NULL,
    dirty_since timestamp with time zone NOT NULL,
    last_enqueued_at timestamp with time zone NOT NULL,
    last_attempt_at timestamp with time zone,
    attempt_count integer DEFAULT 0 NOT NULL,
    last_error text
);

CREATE TABLE public.project_template_organization_access (
    project_id uuid NOT NULL,
    organization_id uuid NOT NULL,
    granted_by uuid,
    granted_at timestamp with time zone NOT NULL
);

CREATE TABLE public.project_thumbnails (
    project_id uuid NOT NULL,
    content_type text NOT NULL,
    updated_by uuid,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE public.project_user_archives (
    project_id uuid NOT NULL,
    user_id uuid NOT NULL,
    archived_at timestamp with time zone NOT NULL
);

CREATE TABLE public.projects (
    id uuid NOT NULL,
    name text NOT NULL,
    description text,
    created_at timestamp with time zone NOT NULL,
    owner_user_id uuid,
    is_template boolean DEFAULT false NOT NULL,
    project_type text DEFAULT 'typst'::text NOT NULL,
    workspace_version bigint DEFAULT 0 NOT NULL,
    content_epoch bigint DEFAULT 0 NOT NULL,
    access_epoch bigint DEFAULT 0 NOT NULL,
    CONSTRAINT projects_project_type_check CHECK ((project_type = ANY (ARRAY['typst'::text, 'latex'::text])))
);

CREATE TABLE public.revision_asset_changes (
    revision_id uuid NOT NULL,
    path text NOT NULL,
    change_kind text NOT NULL,
    object_key text,
    content_type text,
    size_bytes bigint,
    inline_data bytea,
    CONSTRAINT revision_asset_changes_change_kind_check CHECK ((change_kind = ANY (ARRAY['upsert'::text, 'delete'::text])))
);

CREATE TABLE public.revision_assets (
    revision_id uuid NOT NULL,
    path text NOT NULL,
    object_key text NOT NULL,
    content_type text NOT NULL,
    size_bytes bigint NOT NULL,
    inline_data bytea
);

CREATE TABLE public.revision_authors (
    revision_id uuid NOT NULL,
    user_id uuid NOT NULL
);

CREATE TABLE public.revision_directories (
    revision_id uuid NOT NULL,
    path text NOT NULL
);

CREATE TABLE public.revision_directory_changes (
    revision_id uuid NOT NULL,
    path text NOT NULL,
    change_kind text NOT NULL,
    CONSTRAINT revision_directory_changes_change_kind_check CHECK ((change_kind = ANY (ARRAY['upsert'::text, 'delete'::text])))
);

CREATE TABLE public.revision_document_changes (
    revision_id uuid NOT NULL,
    path text NOT NULL,
    change_kind text NOT NULL,
    content text,
    CONSTRAINT revision_document_changes_change_kind_check CHECK ((change_kind = ANY (ARRAY['upsert'::text, 'delete'::text])))
);

CREATE TABLE public.revision_documents (
    revision_id uuid NOT NULL,
    path text NOT NULL,
    content text NOT NULL
);

CREATE TABLE public.revisions (
    id uuid NOT NULL,
    project_id uuid NOT NULL,
    actor_user_id uuid,
    summary text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    entry_file_path text,
    parent_revision_id uuid,
    storage_kind text DEFAULT 'full'::text NOT NULL,
    is_complete boolean DEFAULT true NOT NULL,
    CONSTRAINT revisions_storage_kind_check CHECK ((storage_kind = ANY (ARRAY['full'::text, 'diff'::text])))
);

CREATE TABLE public.user_oidc_groups (
    user_id uuid NOT NULL,
    group_name text NOT NULL,
    synced_at timestamp with time zone NOT NULL
);

CREATE TABLE public.user_login_identities (
    user_id uuid NOT NULL,
    authority_kind text NOT NULL,
    authority_id text NOT NULL,
    subject text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    last_authenticated_at timestamp with time zone NOT NULL,
    CONSTRAINT user_login_identities_authority_kind_check CHECK ((authority_kind = ANY (ARRAY['oidc'::text, 'external_git'::text])))
);

CREATE TABLE public.users (
    id uuid NOT NULL,
    email text NOT NULL,
    display_name text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    username text NOT NULL,
    CONSTRAINT users_username_format CHECK ((username ~ '^[a-z0-9](?:[a-z0-9._-]{0,62}[a-z0-9])$'::text))
);

ALTER TABLE ONLY public.documents ALTER COLUMN change_sequence SET DEFAULT nextval('public.documents_change_sequence_seq'::regclass);

ALTER TABLE ONLY public.anonymous_share_sessions
    ADD CONSTRAINT anonymous_share_sessions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.anonymous_share_sessions
    ADD CONSTRAINT anonymous_share_sessions_session_token_fingerprint_key UNIQUE (session_token_fingerprint);

ALTER TABLE ONLY public.audit_events
    ADD CONSTRAINT audit_events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.auth_sessions
    ADD CONSTRAINT auth_sessions_pkey PRIMARY KEY (session_token_fingerprint);

ALTER TABLE ONLY public.auth_settings
    ADD CONSTRAINT auth_settings_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.collab_doc_latest_snapshots
    ADD CONSTRAINT collab_doc_latest_snapshots_pkey PRIMARY KEY (project_id, document_id, collaboration_revision);

ALTER TABLE ONLY public.collab_doc_updates
    ADD CONSTRAINT collab_doc_updates_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_project_id_path_key UNIQUE (project_id, path);

ALTER TABLE ONLY public.external_git_inbound_jobs
    ADD CONSTRAINT external_git_inbound_jobs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.external_git_oauth_grants
    ADD CONSTRAINT external_git_oauth_grants_pkey PRIMARY KEY (user_id, provider_instance_id);

ALTER TABLE ONLY public.external_git_oauth_grants
    ADD CONSTRAINT external_git_oauth_grants_provider_account_key UNIQUE (provider_instance_id, provider_account_id);

ALTER TABLE ONLY public.external_git_oauth_attempts
    ADD CONSTRAINT external_git_oauth_attempts_pkey PRIMARY KEY (state);

ALTER TABLE ONLY public.external_git_project_links
    ADD CONSTRAINT external_git_project_links_provider_repository_key UNIQUE (provider_instance_id, provider_repository_id);

ALTER TABLE ONLY public.external_git_project_links
    ADD CONSTRAINT external_git_project_links_project_provider_key UNIQUE (project_id, provider_instance_id);

ALTER TABLE ONLY public.git_bundle_artifacts
    ADD CONSTRAINT git_bundle_artifacts_object_key_key UNIQUE (object_key);

ALTER TABLE ONLY public.git_bundle_artifacts
    ADD CONSTRAINT git_bundle_artifacts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.git_pending_authors
    ADD CONSTRAINT git_pending_authors_pkey PRIMARY KEY (project_id, user_id);

ALTER TABLE ONLY public.git_pending_guest_authors
    ADD CONSTRAINT git_pending_guest_authors_pkey PRIMARY KEY (project_id, display_name);

ALTER TABLE ONLY public.git_repositories
    ADD CONSTRAINT git_repositories_pkey PRIMARY KEY (project_id);

ALTER TABLE ONLY public.git_sync_states
    ADD CONSTRAINT git_sync_states_pkey PRIMARY KEY (project_id);

ALTER TABLE ONLY public.external_git_checkpoint_queue
    ADD CONSTRAINT external_git_checkpoint_queue_pkey PRIMARY KEY (project_id);

ALTER TABLE ONLY public.external_git_pending_authors
    ADD CONSTRAINT external_git_pending_authors_pkey PRIMARY KEY (project_id, user_id);

ALTER TABLE ONLY public.external_git_pending_guest_authors
    ADD CONSTRAINT external_git_pending_guest_authors_pkey PRIMARY KEY (project_id, display_name);

ALTER TABLE ONLY public.external_git_project_links
    ADD CONSTRAINT external_git_project_links_pkey PRIMARY KEY (project_id);

ALTER TABLE ONLY public.local_accounts
    ADD CONSTRAINT local_accounts_pkey PRIMARY KEY (user_id);

ALTER TABLE ONLY public.object_deletion_queue
    ADD CONSTRAINT object_deletion_queue_pkey PRIMARY KEY (object_key);

ALTER TABLE ONLY public.oidc_states
    ADD CONSTRAINT oidc_states_pkey PRIMARY KEY (state);

ALTER TABLE ONLY public.org_oidc_group_role_mappings
    ADD CONSTRAINT org_oidc_group_role_mappings_pkey PRIMARY KEY (organization_id, group_name);

ALTER TABLE ONLY public.organization_memberships
    ADD CONSTRAINT organization_memberships_pkey PRIMARY KEY (organization_id, user_id);

ALTER TABLE ONLY public.organizations
    ADD CONSTRAINT organizations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.personal_access_tokens
    ADD CONSTRAINT personal_access_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.personal_access_tokens
    ADD CONSTRAINT personal_access_tokens_token_fingerprint_key UNIQUE (token_fingerprint);

ALTER TABLE ONLY public.project_assets
    ADD CONSTRAINT project_assets_object_key_key UNIQUE (object_key);

ALTER TABLE ONLY public.project_assets
    ADD CONSTRAINT project_assets_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.project_directories
    ADD CONSTRAINT project_directories_pkey PRIMARY KEY (project_id, path);

ALTER TABLE ONLY public.project_group_roles
    ADD CONSTRAINT project_group_roles_pkey PRIMARY KEY (project_id, group_name);

ALTER TABLE ONLY public.project_organization_access
    ADD CONSTRAINT project_organization_access_pkey PRIMARY KEY (project_id, organization_id);

ALTER TABLE ONLY public.project_pdf_artifacts
    ADD CONSTRAINT project_pdf_artifacts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.project_roles
    ADD CONSTRAINT project_roles_pkey PRIMARY KEY (project_id, user_id);

ALTER TABLE ONLY public.project_settings
    ADD CONSTRAINT project_settings_pkey PRIMARY KEY (project_id);

ALTER TABLE ONLY public.project_share_links
    ADD CONSTRAINT project_share_links_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.project_share_links
    ADD CONSTRAINT project_share_links_token_value_key UNIQUE (token_value);

ALTER TABLE ONLY public.project_snapshots
    ADD CONSTRAINT project_snapshots_object_key_key UNIQUE (object_key);

ALTER TABLE ONLY public.project_snapshots
    ADD CONSTRAINT project_snapshots_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.project_sync_queue
    ADD CONSTRAINT project_sync_queue_pkey PRIMARY KEY (project_id);

ALTER TABLE ONLY public.project_template_organization_access
    ADD CONSTRAINT project_template_organization_access_pkey PRIMARY KEY (project_id, organization_id);

ALTER TABLE ONLY public.project_thumbnails
    ADD CONSTRAINT project_thumbnails_pkey PRIMARY KEY (project_id);

ALTER TABLE ONLY public.project_user_archives
    ADD CONSTRAINT project_user_archives_pkey PRIMARY KEY (project_id, user_id);

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.revision_asset_changes
    ADD CONSTRAINT revision_asset_changes_pkey PRIMARY KEY (revision_id, path);

ALTER TABLE ONLY public.revision_assets
    ADD CONSTRAINT revision_assets_pkey PRIMARY KEY (revision_id, path);

ALTER TABLE ONLY public.revision_authors
    ADD CONSTRAINT revision_authors_pkey PRIMARY KEY (revision_id, user_id);

ALTER TABLE ONLY public.revision_directories
    ADD CONSTRAINT revision_directories_pkey PRIMARY KEY (revision_id, path);

ALTER TABLE ONLY public.revision_directory_changes
    ADD CONSTRAINT revision_directory_changes_pkey PRIMARY KEY (revision_id, path);

ALTER TABLE ONLY public.revision_document_changes
    ADD CONSTRAINT revision_document_changes_pkey PRIMARY KEY (revision_id, path);

ALTER TABLE ONLY public.revision_documents
    ADD CONSTRAINT revision_documents_pkey PRIMARY KEY (revision_id, path);

ALTER TABLE ONLY public.revisions
    ADD CONSTRAINT revisions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.user_oidc_groups
    ADD CONSTRAINT user_oidc_groups_pkey PRIMARY KEY (user_id, group_name);

ALTER TABLE ONLY public.user_login_identities
    ADD CONSTRAINT user_login_identities_pkey PRIMARY KEY (authority_kind, authority_id, subject);

ALTER TABLE ONLY public.user_login_identities
    ADD CONSTRAINT user_login_identities_user_authority_key UNIQUE (user_id, authority_kind, authority_id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);

CREATE INDEX external_git_inbound_jobs_due ON public.external_git_inbound_jobs USING btree (state, next_attempt_at, created_at);

CREATE UNIQUE INDEX external_git_inbound_jobs_one_active_project ON public.external_git_inbound_jobs USING btree (project_id) WHERE (state = ANY (ARRAY['pending'::text, 'processing'::text, 'retry_wait'::text, 'paused'::text]));

CREATE INDEX external_git_inbound_jobs_project_history ON public.external_git_inbound_jobs USING btree (project_id, created_at DESC);

CREATE INDEX idx_anonymous_share_sessions_link ON public.anonymous_share_sessions USING btree (share_link_id);

CREATE INDEX idx_anonymous_share_sessions_project ON public.anonymous_share_sessions USING btree (project_id, created_at DESC);

CREATE INDEX idx_audit_events_created ON public.audit_events USING btree (created_at DESC);

CREATE INDEX idx_auth_sessions_expires_at ON public.auth_sessions USING btree (expires_at);

CREATE INDEX idx_auth_sessions_user_id ON public.auth_sessions USING btree (user_id);

CREATE INDEX idx_collab_doc_latest_snapshots_updated ON public.collab_doc_latest_snapshots USING btree (updated_at DESC);

CREATE INDEX idx_collab_doc_updates_document ON public.collab_doc_updates USING btree (project_id, content_epoch, document_id, collaboration_revision, id);

CREATE INDEX idx_comments_project ON public.comments USING btree (project_id, created_at DESC);

CREATE INDEX idx_documents_project ON public.documents USING btree (project_id);

CREATE INDEX idx_documents_project_change_sequence ON public.documents USING btree (project_id, change_sequence);

CREATE INDEX idx_external_git_checkpoint_queue_due ON public.external_git_checkpoint_queue USING btree (state, next_attempt_at);

CREATE INDEX idx_external_git_oauth_grants_status ON public.external_git_oauth_grants USING btree (provider_instance_id, status);

CREATE INDEX idx_external_git_oauth_attempts_expiry ON public.external_git_oauth_attempts USING btree (expires_at);

CREATE INDEX idx_user_login_identities_user_id ON public.user_login_identities USING btree (user_id);

CREATE INDEX idx_external_git_project_links_status ON public.external_git_project_links USING btree (provider_instance_id, status);

CREATE INDEX idx_git_bundle_artifacts_project ON public.git_bundle_artifacts USING btree (project_id, created_at DESC);

CREATE INDEX idx_git_pending_authors_project ON public.git_pending_authors USING btree (project_id);

CREATE INDEX idx_git_pending_guest_authors_project ON public.git_pending_guest_authors USING btree (project_id);

CREATE INDEX idx_org_oidc_group_role_org ON public.org_oidc_group_role_mappings USING btree (organization_id);

CREATE INDEX idx_organization_memberships_user ON public.organization_memberships USING btree (user_id);

CREATE INDEX idx_pat_last_used_at ON public.personal_access_tokens USING btree (last_used_at DESC);

CREATE INDEX idx_pat_user_id ON public.personal_access_tokens USING btree (user_id);

CREATE INDEX idx_project_assets_project ON public.project_assets USING btree (project_id, created_at DESC);

CREATE INDEX idx_project_directories_project ON public.project_directories USING btree (project_id);

CREATE INDEX idx_project_group_roles_project ON public.project_group_roles USING btree (project_id);

CREATE INDEX idx_project_organization_access_org ON public.project_organization_access USING btree (organization_id);

CREATE INDEX idx_project_pdf_artifacts_latest ON public.project_pdf_artifacts USING btree (project_id, created_at DESC);

CREATE UNIQUE INDEX idx_project_share_links_active_unique ON public.project_share_links USING btree (project_id, permission) WHERE (revoked_at IS NULL);

CREATE INDEX idx_project_share_links_project_created ON public.project_share_links USING btree (project_id, created_at DESC);

CREATE INDEX idx_project_snapshots_project ON public.project_snapshots USING btree (project_id, created_at DESC);

CREATE INDEX idx_project_sync_queue_dirty_since ON public.project_sync_queue USING btree (dirty_since);

CREATE INDEX idx_project_template_org_access_org ON public.project_template_organization_access USING btree (organization_id);

CREATE INDEX idx_project_user_archives_user ON public.project_user_archives USING btree (user_id);

CREATE INDEX idx_projects_is_template ON public.projects USING btree (is_template);

CREATE INDEX idx_projects_owner_user ON public.projects USING btree (owner_user_id);

CREATE INDEX idx_revision_asset_changes_revision ON public.revision_asset_changes USING btree (revision_id);

CREATE INDEX idx_revision_assets_revision ON public.revision_assets USING btree (revision_id);

CREATE INDEX idx_revision_authors_revision ON public.revision_authors USING btree (revision_id);

CREATE INDEX idx_revision_directories_revision ON public.revision_directories USING btree (revision_id);

CREATE INDEX idx_revision_directory_changes_revision ON public.revision_directory_changes USING btree (revision_id);

CREATE INDEX idx_revision_document_changes_revision ON public.revision_document_changes USING btree (revision_id);

CREATE INDEX idx_revision_documents_revision ON public.revision_documents USING btree (revision_id);

CREATE INDEX idx_revisions_parent_revision ON public.revisions USING btree (parent_revision_id);

CREATE INDEX idx_revisions_project ON public.revisions USING btree (project_id, created_at DESC);

CREATE INDEX idx_revisions_project_complete_created ON public.revisions USING btree (project_id, created_at DESC, id DESC) WHERE (is_complete = true);

CREATE INDEX idx_user_oidc_groups_user ON public.user_oidc_groups USING btree (user_id);

CREATE INDEX object_deletion_queue_due ON public.object_deletion_queue USING btree (next_attempt_at, created_at);

CREATE UNIQUE INDEX uniq_project_assets_path ON public.project_assets USING btree (project_id, path);

ALTER TABLE ONLY public.anonymous_share_sessions
    ADD CONSTRAINT anonymous_share_sessions_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.anonymous_share_sessions
    ADD CONSTRAINT anonymous_share_sessions_share_link_id_fkey FOREIGN KEY (share_link_id) REFERENCES public.project_share_links(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.audit_events
    ADD CONSTRAINT audit_events_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.auth_sessions
    ADD CONSTRAINT auth_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.collab_doc_latest_snapshots
    ADD CONSTRAINT collab_doc_latest_snapshots_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.collab_doc_latest_snapshots
    ADD CONSTRAINT collab_doc_latest_snapshots_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.collab_doc_updates
    ADD CONSTRAINT collab_doc_updates_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.collab_doc_updates
    ADD CONSTRAINT collab_doc_updates_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.collab_doc_updates
    ADD CONSTRAINT collab_doc_updates_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.external_git_inbound_jobs
    ADD CONSTRAINT external_git_inbound_jobs_project_provider_fkey FOREIGN KEY (project_id, provider_instance_id) REFERENCES public.external_git_project_links(project_id, provider_instance_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.external_git_inbound_jobs
    ADD CONSTRAINT external_git_inbound_jobs_requested_by_user_id_fkey FOREIGN KEY (requested_by_user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.git_bundle_artifacts
    ADD CONSTRAINT git_bundle_artifacts_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.git_pending_authors
    ADD CONSTRAINT git_pending_authors_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.git_pending_authors
    ADD CONSTRAINT git_pending_authors_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.git_pending_guest_authors
    ADD CONSTRAINT git_pending_guest_authors_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.git_repositories
    ADD CONSTRAINT git_repositories_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.git_sync_states
    ADD CONSTRAINT git_sync_states_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.external_git_checkpoint_queue
    ADD CONSTRAINT external_git_checkpoint_queue_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.external_git_project_links(project_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.external_git_oauth_grants
    ADD CONSTRAINT external_git_oauth_grants_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.external_git_oauth_attempts
    ADD CONSTRAINT external_git_oauth_attempts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.external_git_pending_authors
    ADD CONSTRAINT external_git_pending_authors_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.external_git_project_links(project_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.external_git_pending_authors
    ADD CONSTRAINT external_git_pending_authors_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.external_git_pending_guest_authors
    ADD CONSTRAINT external_git_pending_guest_authors_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.external_git_project_links(project_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.external_git_project_links
    ADD CONSTRAINT external_git_project_links_linked_by_user_id_fkey FOREIGN KEY (linked_by_user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.external_git_project_links
    ADD CONSTRAINT external_git_project_links_connector_provider_fkey FOREIGN KEY (linked_by_user_id, provider_instance_id) REFERENCES public.external_git_oauth_grants(user_id, provider_instance_id);

ALTER TABLE ONLY public.external_git_project_links
    ADD CONSTRAINT external_git_project_links_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.local_accounts
    ADD CONSTRAINT local_accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.org_oidc_group_role_mappings
    ADD CONSTRAINT org_oidc_group_role_mappings_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.organization_memberships
    ADD CONSTRAINT organization_memberships_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.organization_memberships
    ADD CONSTRAINT organization_memberships_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.personal_access_tokens
    ADD CONSTRAINT personal_access_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.project_assets
    ADD CONSTRAINT project_assets_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.project_assets
    ADD CONSTRAINT project_assets_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id);

ALTER TABLE ONLY public.project_directories
    ADD CONSTRAINT project_directories_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.project_group_roles
    ADD CONSTRAINT project_group_roles_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.project_organization_access
    ADD CONSTRAINT project_organization_access_granted_by_fkey FOREIGN KEY (granted_by) REFERENCES public.users(id);

ALTER TABLE ONLY public.project_organization_access
    ADD CONSTRAINT project_organization_access_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.project_organization_access
    ADD CONSTRAINT project_organization_access_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.project_pdf_artifacts
    ADD CONSTRAINT project_pdf_artifacts_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id);

ALTER TABLE ONLY public.project_pdf_artifacts
    ADD CONSTRAINT project_pdf_artifacts_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.project_roles
    ADD CONSTRAINT project_roles_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.project_roles
    ADD CONSTRAINT project_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.project_settings
    ADD CONSTRAINT project_settings_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.project_share_links
    ADD CONSTRAINT project_share_links_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id);

ALTER TABLE ONLY public.project_share_links
    ADD CONSTRAINT project_share_links_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.project_snapshots
    ADD CONSTRAINT project_snapshots_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id);

ALTER TABLE ONLY public.project_snapshots
    ADD CONSTRAINT project_snapshots_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.project_sync_queue
    ADD CONSTRAINT project_sync_queue_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.project_template_organization_access
    ADD CONSTRAINT project_template_organization_access_granted_by_fkey FOREIGN KEY (granted_by) REFERENCES public.users(id);

ALTER TABLE ONLY public.project_template_organization_access
    ADD CONSTRAINT project_template_organization_access_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.project_template_organization_access
    ADD CONSTRAINT project_template_organization_access_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.project_thumbnails
    ADD CONSTRAINT project_thumbnails_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.project_thumbnails
    ADD CONSTRAINT project_thumbnails_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id);

ALTER TABLE ONLY public.project_user_archives
    ADD CONSTRAINT project_user_archives_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.project_user_archives
    ADD CONSTRAINT project_user_archives_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.revision_asset_changes
    ADD CONSTRAINT revision_asset_changes_revision_id_fkey FOREIGN KEY (revision_id) REFERENCES public.revisions(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.revision_assets
    ADD CONSTRAINT revision_assets_revision_id_fkey FOREIGN KEY (revision_id) REFERENCES public.revisions(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.revision_authors
    ADD CONSTRAINT revision_authors_revision_id_fkey FOREIGN KEY (revision_id) REFERENCES public.revisions(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.revision_authors
    ADD CONSTRAINT revision_authors_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.revision_directories
    ADD CONSTRAINT revision_directories_revision_id_fkey FOREIGN KEY (revision_id) REFERENCES public.revisions(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.revision_directory_changes
    ADD CONSTRAINT revision_directory_changes_revision_id_fkey FOREIGN KEY (revision_id) REFERENCES public.revisions(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.revision_document_changes
    ADD CONSTRAINT revision_document_changes_revision_id_fkey FOREIGN KEY (revision_id) REFERENCES public.revisions(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.revision_documents
    ADD CONSTRAINT revision_documents_revision_id_fkey FOREIGN KEY (revision_id) REFERENCES public.revisions(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.revisions
    ADD CONSTRAINT revisions_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.revisions
    ADD CONSTRAINT revisions_parent_revision_id_fkey FOREIGN KEY (parent_revision_id) REFERENCES public.revisions(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.revisions
    ADD CONSTRAINT revisions_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.user_oidc_groups
    ADD CONSTRAINT user_oidc_groups_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.user_login_identities
    ADD CONSTRAINT user_login_identities_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

-- Runtime configuration expects the singleton settings row to exist.
INSERT INTO public.auth_settings (
    id,
    allow_local_login,
    allow_local_registration,
    allow_oidc,
    oidc_issuer,
    oidc_client_id,
    oidc_client_secret,
    oidc_redirect_uri,
    oidc_groups_claim,
    updated_at
)
VALUES (1, true, true, true, NULL, NULL, NULL, NULL, 'groups', now());

-- Site administrators are owners of this dedicated system organization.
INSERT INTO public.organizations (id, name, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'Site Admins', now());
